### ISSUE TITLE
Vim key bindings?

### ISSUE THREAD

**Issue by sarjann** [nick42d/youtui#10]
Would it be possible to implement some basic vim bindings? hjkl and / to access search

**Comment by nick42d** [comment]
Yes, it's possible, although I need to make sure this does not stop me in future from adding configurable keybinds. I could see people wanting to take this a bit further and wanting to implement more vim/helix like keybinds, are there any others you'd find useful?

**Comment by nick42d** [comment]
Resolved in #185 by allowing users to remap custom keybinds, including vim keybinds. These are set by modifying your `config.toml`. An example `config.toml` with vim keybinds mapped is provided in the `./youtui/config/` directory.
