### ISSUE TITLE
Song download: 403 forbidden

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#133]
When attempting to play a track, I'm getting the 403 HTTP response, which eventually maxes out allowed retries:

![image](https://github.com/user-attachments/assets/edf902ee-b3d9-4b22-996f-98e777b7de10)

This doesn't happen always. Not sure how to reproduce consistently.

**Comment by nick42d** [comment]
Related issue: https://github.com/Mithronn/rusty_ytdl/issues/31.

**Comment by nick42d** [comment]
@rkratky I believe #134 (now merged to main) has resolved this. Would you be able to test from your side?

**Comment by rkratky** [comment]
Yes, seems to be fixed.
