### ISSUE TITLE
API: thumbnails not found in Api response

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#144]
branch: iss143-test-audio-quality

I don't think I saw this before:

![image](https://github.com/user-attachments/assets/404e042d-e688-4a01-878a-94db86bbf282)

Strangely, it happened with a query that worked just seconds before.

**Comment by rkratky** [comment]
After the first occurrence of this error, the same query never worked again (the number of results was displayed -- just not the actual results). Restarting the program fixed it, and I can't reproduce it anymore :/

**Comment by nick42d** [comment]
I have been able to reproduce this with `youtui get-album MPREb_HzRLg8XTLkv`. Let me take a look. Looks like a good case for #129 too, I should log failed 'test.json's for all queries (in a temp directory).

**Comment by nick42d** [comment]
Various Artists doesn't have a thumbnail, so seems that this should be an optional field.
![image](https://github.com/user-attachments/assets/7b665960-17b4-496d-b40b-16eabe781a7c)

**Comment by nick42d** [comment]
Would also impact playlists; `youtui get-playlist VLRDCLAK5uy_lMzHW51iFg1Kx0d_2EHpzbOgCrwtu8cgI`
