### ISSUE TITLE
Missing: 'Clear filter'

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#146]
I see the possibility to 'Clear sort', but there's no way to clear filter settings -- they just keep on being added (incl. empty filter). So, not only one cannot remove a filter to see all search results again (and/or start filtering from scratch), the filter also causes new search results to be filtered (thus often causing no results to be displayed).

![image](https://github.com/user-attachments/assets/c6993a5d-9049-43ea-9ee8-989c89fa6a47)

**Comment by nick42d** [comment]
This should by accessible by pressing 'Filter (F3)' and then 'Clear Filter (F6)'.
![image](https://github.com/user-attachments/assets/29624c42-d37f-4a71-88e5-7a7b83e5eff6)

**Comment by rkratky** [comment]
Ah, nice. I didn't notice that :)
