### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by sgmihai** [nick42d/youtui#16]
tried
cargo +nightly install youtui
al well as
cargo  install youtui
both fail to compile:
https://pastebin.com/raw/gXx78tg5

**Comment by nick42d** [comment]
Seems on update to ratatui library breaks install. I can replicate here too. Will revert.

**Comment by nick42d** [comment]
Resolved in v0.0.4, please try again with `cargo install youtui`.

**Comment by joshka** [comment]
`--locked` is the usual approach to ensure you're using the same version of dependencies as is specified in the lock file. It's worth adding this to any app's install instructions.

Also, you might want to look into cargo-binstall as an option (this will pull directly from your github artifacts if you release these as part of your release process). This is generally much faster than recompiling everything.
