### ISSUE TITLE
panicked at ytmapi-rs/src/parse/artist.rs:169:56: not yet implemented

### ISSUE THREAD

**Issue by rkratky** [nick42d/youtui#160]
The error is shown on a blank screen (i.e. the UI disappears and is replaced by this text only) following:

1. Search for 'classical music'.
2. Select one of the following:
   * Deutsche Grammophon - DG
   * Warner Classics
   * Naxos Music
   * Sony Classical

The program doesn't recover, though pressing Enter brings up a mangled, non-responsive part of the UI:
![image](https://github.com/user-attachments/assets/d993d578-d013-4f62-a08b-52ba35890ac4)

**Comment by rkratky** [comment]
Btw, playback continues uniterrupted.

**Comment by nick42d** [comment]
Welp, that's the first time someone's triggered that branch in GetArtistQuery it seems. Think I know what needs fixing. Could be an opportunity to improve the panic handling too.

**Comment by nick42d** [comment]
Resolved in #161, panic code should be more robust now too, you should no longer get a glitchy crash if you find another panic.
