### ISSUE TITLE
Some Menu's text is white dispite light theme

### ISSUE THREAD

**Issue by SeseMueller** [nick42d/youtui#5]
Some Menus, like the search results as well as the one that pops up when a song is selected have text that isn't dynamic. 

This means that it is white, even when the theme is light, making it very hard to read.

Example:
<img width="337" alt="Bildschirmfoto 2023-12-04 um 12 01 55" src="https://github.com/nick42d/youtui/assets/44344995/9a0503e4-dddb-4cc3-b6bd-cecfde0e4aa2">

(The text would be completely unreadable if my terminal wasn't partially transparent)

**Comment by nick42d** [comment]
Thanks for the report!
It looks like I am explicitly colouring the block panels in the browser and header, and the text in the search suggestions and key entry modal.
It was not noticeable in my terminal with a dark theme.
I'm hoping to add theming in a future release, but for now, this should be simple to fix.

**Comment by nick42d** [comment]
Fixed in https://github.com/nick42d/youtui/commit/de5ac77baa6a48aa825dabbde4768fc65c8c9607
